#!/usr/bin/env python
#
# vmnetx - Virtual machine network execution
#
# Copyright (C) 2012 Carnegie Mellon University
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of version 2 of the GNU General Public License as published
# by the Free Software Foundation.  A copy of the GNU General Public License
# should have been distributed along with this program in the file
# COPYING.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#

from optparse import OptionParser
import sys

import vmnetx
from vmnetx.app import VMNetXApp

USAGE = 'Usage: %prog [options] manifest_file'
VERSION = '%prog ' + vmnetx.__version__
DESCRIPTION = 'Execute a VMNetX virtual machine.'

parser = OptionParser(usage=USAGE, version=VERSION, description=DESCRIPTION)
opts, args = parser.parse_args()
if len(args) != 1:
    parser.error('Incorrect mandatory argument')
manifest_file = args[0]

try:
    app = VMNetXApp(manifest_file)
    app.run()
except Exception, e:
    print str(e)
    sys.exit(1)
